{
 "title": "Polygon validators performance",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Tracked validators miss rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select \n\tavg(case when fulfilled = false then 1 else 0 end)\nfrom duties\nWHERE\n  $__unixEpochFilter(\"blockTimestamp\") AND\n  \"isTracked\" = true"
    }
   ]
  },
  {
   "title": "Tracked validators misses",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(\"blockTimestamp\",$__interval),\n  count(*)\nFROM duties\nWHERE\n  $__unixEpochFilter(\"blockTimestamp\") AND\n  fulfilled = false AND\n  \"isTracked\" = true\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total checkpoints",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM checkpoints\nWHERE\n  $__unixEpochFilter(\"blockTimestamp\")"
    }
   ]
  },
  {
   "title": "Missed by tracked validators",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  moniker AS metric,\n  count(*)\nFROM duties\nWHERE\n  $__unixEpochFilter(\"blockTimestamp\") AND\n  fulfilled = false AND\n  \"isTracked\" = true\nGROUP BY moniker\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Checkpoints missed by tracked validators",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select \n\tmoniker,\n\t\"checkpointNumber\"\nfrom duties\nWHERE\n  $__unixEpochFilter(\"blockTimestamp\") AND\n  \"isTracked\" = true AND\n  fulfilled = false;"
    }
   ]
  },
  {
   "title": "Last checkpoint",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"number\" AS \"value\"\nFROM checkpoints\nWHERE\n  $__unixEpochFilter(\"blockTimestamp\")\nORDER BY \"blockTimestamp\" DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT\n  \"blockTimestamp\" * 1000 AS \"value\"\nFROM checkpoints\nWHERE\n  $__unixEpochFilter(\"blockTimestamp\")\nORDER BY \"blockTimestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Index delay",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - polygon_validators_monitoring_last_processed_block_timestamp_unix"
    }
   ]
  },
  {
   "title": "Uptime <100% within the time range",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select\n  \"isTracked\" as tracked,\n\tmoniker,\n\tavg(case when fulfilled = false then 0 else 1 end) as value\nfrom duties\nWHERE\n  $__unixEpochFilter(\"blockTimestamp\")\ngroup by 1,2;"
    }
   ]
  },
  {
   "title": "Checkpoints head",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"blockTimestamp\" AS \"time\",\n  number\nFROM checkpoints\nWHERE\n  $__unixEpochFilter(\"blockTimestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Checkpoints by 24 hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(\"blockTimestamp\",24h),\n  count(number) AS \"value\"\nFROM checkpoints\nWHERE\n  $__unixEpochFilter(\"blockTimestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Validators uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"blockTimestamp\" AS \"time\",\n  labels ->> 'moniker' AS metric,\n  value\nFROM metrics\nWHERE\n  $__unixEpochFilter(\"blockTimestamp\") AND\n  name = 'tracked_vals_perf_rate'\nORDER BY 1,2;"
    },
    {
     "rawSql": "SELECT\n  \"blockTimestamp\" AS \"time\",\n  'AVG' AS metric,\n  value\nFROM metrics\nWHERE\n  $__unixEpochFilter(\"blockTimestamp\") AND\n  name = 'avg_vals_perf_rate'\nORDER BY 1;"
    },
    {
     "rawSql": "SELECT\n  \"blockTimestamp\" AS \"time\",\n  'TOP' AS metric,\n  value\nFROM metrics\nWHERE\n  $__unixEpochFilter(\"blockTimestamp\") AND\n  name = 'top_vals_perf_rate'\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Stake events in MATIC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(\"blockTimestamp\",$__interval),\n  moniker AS metric,\n  sum(amount) AS \"amount\"\nFROM share_events\nWHERE\n  $__unixEpochFilter(\"blockTimestamp\") and\n  \"type\" = 'Minted'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Stake distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  moniker, \n  SUM (\n    CASE se.\"type\" WHEN 'Minted' THEN se.amount ELSE - se.amount END\n  ) \nFROM \n  share_events se \nGROUP BY \n  se.moniker;"
    }
   ]
  },
  {
   "title": "Unstake events in MATIC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(\"blockTimestamp\",$__interval),\n  moniker AS metric,\n  sum(amount) AS \"amount\"\nFROM share_events\nWHERE\n  $__unixEpochFilter(\"blockTimestamp\") and\n  \"type\" = 'Burned'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}