{
 "title": "Status",
 "description": "https://www.notion.so/Polygon-validators-monitoring-b25e625e2cec4ca0b82e642c7ba0dbcf",
 "tags": [
  "bot",
  "automation",
  "apps"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "container", "query": "polygon-validators-monitoring" },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(polygon_validators_monitoring_build_info, env)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values(polygon_validators_monitoring_build_info{env=~\"$env\"}, source)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(polygon_validators_monitoring_build_info{env=~\"$env\", source=~\"$source\"}, instance)"
    }
   },
   { "name": "search", "label": "Search query" }
  ]
 },
 "panels": [
  {
   "title": "Build info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tag",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "polygon_validators_monitoring_build_info"
      }
     ]
    },
    {
     "title": "Branch",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "polygon_validators_monitoring_build_info"
      }
     ]
    },
    {
     "title": "Commit",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "polygon_validators_monitoring_build_info"
      }
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Bot uptime",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - polygon_validators_monitoring_process_start_time_seconds{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Index delay",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - polygon_validators_monitoring_last_processed_block_timestamp_unix{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg tasks duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(polygon_validators_monitoring_tasks_durations_seconds_sum[$__range]) / rate(polygon_validators_monitoring_tasks_durations_seconds_count[$__range])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fails count",
   "type": "stat",
   "description": "Count of fails for the given tasks",
   "gridPos": { "h": 3, "w": 7, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(polygon_validators_monitoring_tasks_durations_seconds_count{env=~\"$env\",source=~\"$source\",instance=~\"$instance\",status=\"failure\"}[$__range])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ETH RPC errors count",
   "type": "stat",
   "description": "Count errors during RPC requests",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(polygon_validators_monitoring_el_rpc_requests_duration_seconds_count{env=~\"$env\",source=~\"$source\",instance=~\"$instance\",status=\"failure\"}[$__range])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "EL requests count",
   "type": "stat",
   "description": "Count of requests to EL RPC node ",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(polygon_validators_monitoring_el_rpc_requests_duration_seconds_count{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}[$__range])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "RPC requests duration ($instance)",
   "type": "heatmap",
   "description": "Duration of requests to the RPC provider",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(polygon_validators_monitoring_el_rpc_requests_duration_seconds_bucket{env=~\"$env\",source=~\"$source\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "RPC requests errors",
   "type": "timeseries",
   "description": "Number of request errors to the RPC provider",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(polygon_validators_monitoring_el_rpc_requests_duration_seconds_count{env=~\"$env\",source=~\"$source\",instance=~\"$instance\",status=\"failure\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "{container_name=\"$container\",env=~\"$env\",source=~\"$source\"} | json | line_format \"[{{.level}}] {{.message}}\" |~ \"$search\""
      }
     ]
    },
    {
     "title": "Error logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "{container_name=\"$container\",env=~\"$env\",source=~\"$source\"} | json |= \"ERROR\" | line_format \"[{{.levelname}}] {{.message}}\" |~ \"$search\""
      }
     ]
    }
   ]
  },
  {
   "title": "Resources usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "Cumulative cpu time consumed",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(irate(polygon_validators_monitoring_process_cpu_user_seconds_total{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}[5m])) by (instance) *100) + (sum(irate(polygon_validators_monitoring_process_cpu_seconds_total{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}[5m])) by (instance) *100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(polygon_validators_monitoring_process_resident_memory_bytes{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Opened FDs",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "polygon_validators_monitoring_process_open_fds{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "FDs"
      }
     ]
    },
    {
     "title": "Network traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum(irate(container_network_receive_bytes_total{env=~\"$env\",source=~\"$source\",name=~\"$container\"}[5m])) by (name)) + (sum(irate(container_network_transmit_bytes_total{env=~\"$env\",source=~\"$source\",name=~\"$container\"}[5m])) by (name))",
       "legendFormat": "net"
      }
     ]
    }
   ]
  },
  {
   "title": "Node JS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC duration (major)",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(polygon_validators_monitoring_nodejs_gc_duration_seconds_bucket{env=~\"$env\",source=~\"$source\",instance=~\"$instance\",kind=\"major\"}[1m])) by (le)"
      }
     ]
    },
    {
     "title": "GC duration (minor)",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(polygon_validators_monitoring_nodejs_gc_duration_seconds_bucket{env=~\"$env\",source=~\"$source\",instance=~\"$instance\",kind=\"minor\"}[1m])) by (le)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC duration (incremental)",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(polygon_validators_monitoring_nodejs_gc_duration_seconds_bucket{env=~\"$env\",source=~\"$source\",instance=~\"$instance\",kind=\"incremental\"}[1m])) by (le)"
      }
     ]
    },
    {
     "title": "Heap size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "polygon_validators_monitoring_nodejs_heap_size_used_bytes{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "used"
      },
      {
       "expr": "polygon_validators_monitoring_nodejs_heap_size_total_bytes{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Heap space size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "polygon_validators_monitoring_nodejs_heap_space_size_used_bytes{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "{{space}}"
      },
      {
       "expr": "sum(polygon_validators_monitoring_nodejs_heap_space_size_total_bytes{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Eventloop lag",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "polygon_validators_monitoring_nodejs_eventloop_lag_min_seconds{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "min"
      },
      {
       "expr": "polygon_validators_monitoring_nodejs_eventloop_lag_mean_seconds{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "mean"
      },
      {
       "expr": "polygon_validators_monitoring_nodejs_eventloop_lag_max_seconds{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Eventloop lag (percentiles)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(polygon_validators_monitoring_nodejs_eventloop_lag_p50_seconds{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "p50"
      },
      {
       "expr": "sum(rate(polygon_validators_monitoring_nodejs_eventloop_lag_p90_seconds{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "p90"
      },
      {
       "expr": "sum(rate(polygon_validators_monitoring_nodejs_eventloop_lag_p99_seconds{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  }
 ]
}